### ISSUE TITLE
Возможность проброса дополнительных настроек курла

### ISSUE THREAD

**Issue by Aliance** [alxmsl/Network#1]
Вот [здесь](https://github.com/alxmsl/Network/blob/master/source/Http/CurlTransport.php#L85), где устанавливаются настройки курла, нет возможности передать что-то своё. А это не гуд, мне например потребовалось установить `CURLOPT_FOLLOWLOCATION`. Предлагаю сделать проброс дополнительных настроек, код уже есть, ты как на это смотришь?

**Comment by alxmsl** [comment]
Положительно, но решение из #3 считаю не правильным, потому что curl - это транспорт, и привязывать параметры транспорта к классу запроса кажется мне некрасивым

**Comment by Aliance** [comment]
Согласен, было бы более правильно, если бы в объект запроса передавался бы объект транспорта (с проставленными опциями). Но сейчас передается лишь константа для фабричного метода выбора используемого транспорта. Да и в целом, кроме курла ничего на данный момент не поддерживается. Так что как быстрый вариант - выбрал именно такой. Если все же когда-то появится второй транспорт - можно будет отрефакторить как я описал выше.

**Comment by Aliance** [comment]
Добавил в классе запроса геттер для транспорта, теперь можно будет вызывать метод у самого объекта транспорта, через объект запроса.

**Comment by alxmsl** [comment]
Да, так будет попизже

**Comment by Aliance** [comment]
Ребейзить?

**Comment by alxmsl** [comment]
Я не против

**Comment by Aliance** [comment]
Готово

**Comment by alxmsl** [comment]
[v1.1.1](https://github.com/alxmsl/Network/releases/tag/v1.1.1)
