### ISSUE TITLE
Переданный url изменяется

### ISSUE THREAD

**Issue by Aliance** [alxmsl/Network#2]
[Вот здесь](https://github.com/alxmsl/Network/blob/ab2cb4c0daa87f382375d95781897a03a6204716/source/Http/CurlTransport.php#L204-L218) у тебя используется метод, дополняющий переданный url какими-то данными. При этом обрезается завершаюший `/`, что в рамках работы с тем же ТФ критично. Получается на вход я даю url `http://topface.com/partner-api/`, а на выходе получаю `http://topface.com/partner-api` И как итог ошибку. Может быть стоит вначале метода проверять, что если данных вовсе нет (как у меня) - то ничего не делать с оригинальным url?

**Comment by alxmsl** [comment]
для такого поведения можно использовать вызов

``` php
CurlTransport::addUrlData($url, [
    '' => '',
])
```

Или через запрос:

``` php
Request::addUrlField('', '')
```

**Comment by Aliance** [comment]
Там конечный `/` же все равно удалится, разве нет?

**Comment by alxmsl** [comment]
Нет, должен остаться

**Comment by Aliance** [comment]
Проверил, остаётся, но это очень похоже на костыль.

**Comment by alxmsl** [comment]
[v1.1.2](https://github.com/alxmsl/Network/releases/tag/v1.1.2) выложено
